definitions:
  scripts:
    - &set_android_sdk_location
      name: Set Android SDK location
      script: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
    - &chmod_gradlew
      name: Make gradlew executable
      script: |
        chmod +x ./gradlew
workflows:
  development-workflow:
    name: Build Development WInP App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
    scripts:
      - *set_android_sdk_location
      - *chmod_gradlew
      - name: Build Android App
        script: |
          ./gradlew app:assembleDevelopDebug
    artifacts:
      - app/build/outputs/apk/develop/debug/*
    publishing:
      email:
        recipients:
          - ogtkzk712@gmail.com
        notify:
          success: true
          failure: true
  staging-workflow:
    name: Build Staging WInP App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
      android_signing:
        - winp_keystore
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: staging
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - *chmod_gradlew
      - *set_android_sdk_location
      - name: Lint App
        script: |
          ./gradlew app:lintStagingRelease
      - name: Build Android App
        script: |
          ./gradlew app:bundleStagingRelease
    artifacts:
      - app/build/outputs/bundle/stagingRelease/*
    publishing:
      email:
        recipients:
          - ogtkzk712@gmail.com
        notify:
          success: true
          failure: true
  production-workflow:
    name: Build Production WInP App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
      android_signing:
        - winp_keystore
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.ogata_k.mobile.winp"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - *chmod_gradlew
      - *set_android_sdk_location
      - name: Lint App
        script: |
          ./gradlew app:lintProductRelease
      - name: Build Android App
        script: |
          ./gradlew app:bundleProductRelease
    artifacts:
      - app/build/outputs/bundle/productRelease/*
    publishing:
      email:
        recipients:
          - ogtkzk712@gmail.com
        notify:
          success: true
          failure: true
      # TODO Google Playの設定を対応した後にコメントアウトを解除する
      #google_play:
      #  credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #  track: internal
      #  submit_as_draft: true
