definitions:
  scripts:
    - &set_android_sdk_location
      name: Set Android SDK location
      script: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
    - &chmod_gradlew
      name: Make gradlew executable
      script: |
        chmod +x ./gradlew
workflows:
  development-workflow:
    name: Build Development WInP App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
    scripts:
      - *set_android_sdk_location
      - *chmod_gradlew
      - name: Build Android App For apk
        script: |
          ./gradlew app:assembleDevelopDebug
    artifacts:
      - app/build/outputs/apk/develop/debug/*
    publishing:
      email:
        recipients:
          - ogtkzk712@gmail.com
        notify:
          success: true
          failure: true
  staging-workflow:
    name: Build Staging WInP App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
      android_signing:
        - winp_keystore
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'staging'
      cancel_previous_builds: true
    scripts:
      - *chmod_gradlew
      - *set_android_sdk_location
      - name: Lint App
        script: |
          ./gradlew app:lintStagingRelease
      - name: Build Android App For aab
        script: |
          ./gradlew app:bundleStagingRelease
      - name: Build Android App For apk
        script: |
          ./gradlew app:assembleStagingRelease
    artifacts:
      - app/build/outputs/bundle/stagingRelease/*
      - app/build/outputs/mapping/stagingRelease/*
      - app/build/intermediates/stripped_native_libs/stagingRelease/stripStagingReleaseDebugSymbols/out/lib
      - app/build/outputs/apk/staging/release/*
    publishing:
      email:
        recipients:
          - ogtkzk712@gmail.com
        notify:
          success: true
          failure: true
  production-workflow:
    name: Build Production WInP App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
      android_signing:
        - winp_keystore
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.ogata_k.mobile.winp"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
      cancel_previous_builds: true
    scripts:
      - *chmod_gradlew
      - *set_android_sdk_location
      - name: Lint App
        script: |
          ./gradlew app:lintProductRelease
      - name: Build Android App For aab with update build number
        script: |
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]
            then
              # fallback in case no build number was found from Google Play.
              # Alternatively, you can `exit 1` to fail the build
              # BUILD_NUMBER is a Codemagic built-in variable tracking the number of
              # times this workflow has been built
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
            else
              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi

          # "1.0.x"のようなバージョン名はbuild.gradle.ktsで自前で管理する。
          ./gradlew bundleProductRelease -PversionCode=$UPDATED_BUILD_NUMBER
    artifacts:
      - app/build/outputs/bundle/productRelease/*
      - app/build/outputs/mapping/productRelease/*
      - app/build/intermediates/stripped_native_libs/productRelease/stripProductReleaseDebugSymbols/out/lib
    publishing:
      email:
        recipients:
          - ogtkzk712@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
