definitions:
  scripts:
    - &pre_build_script
      name: Pre-Build Script
      script: |
        echo "Installing NDK"
        curl -o $FCI_BUILD_DIR/ndk.zip https://dl.google.com/android/repository/android-ndk-r27-darwin-x86_64.zip\?hl\=ja
        unzip -o $FCI_BUILD_DIR/ndk.zip -d $FCI_BUILD_DIR
        echo "ndk.dir=$FCI_BUILD_DIR/android-ndk-r21e" > "$FCI_BUILD_DIR/android/local.properties"
    - &set_android_sdk_location
      name: Set Android SDK location
      script: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
    - &chmod_gradlew
      name: Make gradlew executable
      script: |
        chmod +x ./gradlew
workflows:
  development-workflow:
    name: Build Development WInP App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
      # ndk: r27
    scripts:
      - *pre_build_script
      - *set_android_sdk_location
      - *chmod_gradlew
      - name: Build Android App For apk
        script: |
          ./gradlew app:assembleDevelopDebug --info
    artifacts:
      - app/build/outputs/apk/develop/debug/*
    publishing:
      email:
        recipients:
          - ogtkzk712@gmail.com
        notify:
          success: true
          failure: true
  staging-workflow:
    name: Build Staging WInP App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
      # ndk: r27
      android_signing:
        - winp_keystore
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'staging'
      cancel_previous_builds: true
    scripts:
      - *pre_build_script
      - *chmod_gradlew
      - *set_android_sdk_location
      - name: Lint App
        script: |
          ./gradlew app:lintStagingRelease --info
      - name: Build Android App For aab
        script: |
          ./gradlew app:bundleStagingRelease --info
      - name: Build Android App For apk
        script: |
          ./gradlew app:assembleStagingRelease --info
    artifacts:
      - app/build/outputs/bundle/stagingRelease/*
      - app/build/outputs/mapping/stagingRelease/*
      - app/build/outputs/apk/staging/release/*
    publishing:
      email:
        recipients:
          - ogtkzk712@gmail.com
        notify:
          success: true
          failure: true
  production-workflow:
    name: Build Production WInP App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
      # ndk: r27
      android_signing:
        - winp_keystore
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.ogata_k.mobile.winp"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
      cancel_previous_builds: true
    scripts:
      - *pre_build_script
      - *chmod_gradlew
      - *set_android_sdk_location
      - name: Lint App
        script: |
          ./gradlew app:lintProductRelease --info
      - name: Build Android App For aab
        script: |
          ./gradlew app:bundleProductRelease --info
      - name: Build Android App For apk
        script: |
          ./gradlew app:assembleProductRelease --info
    artifacts:
      - app/build/outputs/bundle/productRelease/*
      - app/build/outputs/mapping/productRelease/*
      - app/build/outputs/apk/staging/release/*
    publishing:
      email:
        recipients:
          - ogtkzk712@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
